# Generated by Django 5.1.2 on 2024-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory_alter_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
