# Generated by Django 5.1.2 on 2024-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newscategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
