# Generated by Django 5.1.2 on 2024-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
