# Generated by Django 5.1.2 on 2024-11-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newsarticle_summery_newsarticlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
